name: Build OverflowProject
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-18.04
    container: archlinux
    steps:
    - name: Setup
      run: |
          pacman -Syu --noconfirm sudo
          sudo pacman --noconfirm -S wget wt rapidjson gtest boost cmake gcc make git
    - uses: actions/checkout@v2.4.0
    - name: Build
      run: |
          sudo mkdir ~/build
          cd ~/build
          sudo cmake $GITHUB_WORKSPACE
          sudo make main
          cd $GITHUB_WORKSPACE
          sudo git config --global user.name 'Build Bot'
          sudo git config --global user.email 'buildbot@github.com'
          sudo git switch --orphan build
          sudo cp -rf ~/build build
          sudo git add -f build
          sudo git commit -am "Automated build"
          sudo git push -f origin build
