name: Build OverflowProject
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-18.04
    container: archlinux
    steps:
    - name: Setup
      run: |
          pacman -Syu --noconfirm sudo
          sudo pacman --noconfirm -S wget wt rapidjson gtest boost cmake gcc make git
    - uses: actions/checkout@v2.4.0
    - name: Build
      run: |
          sudo mkdir $GITHUB_WORKSPACE/build
          cd $GITHUB_WORKSPACE/build
          sudo cmake ..
          sudo make main
          cd ..
          sudo git config --global user.name 'Build Bot'
          sudo git config --global user.email 'buildbot@github.com'
          sudo git switch -c build
          sudo git checkout main -- build
          sudo git add build
          sudo git commit -am "Automated build"
          sudo git push origin build
