name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: Joshua-Ashton/arch-mingw-github-action@v5
    - with:
        command: |
          sudo pacman -Syyu
          sudo pacman -S gtest wt cmake boost rapidjson
