name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    container: archlinux
    steps:
    - name: Arch Linux
      run: |
          sudo pacman -Syyu
          sudo pacman --noconfirm -S gtest wt cmake boost rapidjson ngrok
          sudo wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tgz
          sudo tar xvzf ~/Downloads/ngrok-stable-linux-amd64.tgz -C /usr/local/bin
          sudo ngrok http 9090
          sudo wget https://github.com/ilyasssklimov/OverflowProject/blob/main/main
          sudo wget https://github.com/ilyasssklimov/OverflowProject/blob/main/info.xml
