name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: Joshua-Ashton/arch-mingw-github-action@v5
    - name: Docker hello-world
      run: |
        sudo pacman --noconfirm -Syu docker
        sudo systemctl start docker
        docker run --rm hello-world
