name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-21.10
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install witty witty-dev witty-doc witty-dbg witty-examples
