name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Arch Linux
      uses: Joshua-Ashton/arch-mingw-github-action@v5
      with:
        command: |
          sudo pacman -Syyu
          sudo pacman --noconfirm -S gtest wt cmake boost rapidjson
    - name: Ngrok Tunneling
      uses: vmactions/ngrok-tunnel@v0.0.1
      with:
        # tcp or http
        protocol: http # optional
        # port to forward to
        port: 9090
        command: |
          ls
      
