name: Run OverflowProject
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-18.04
    container: archlinux
    steps:
    - name: Setup
      run: |
          pacman -Syu --noconfirm sudo
          sudo pacman --noconfirm -S wget wt curl
          sudo wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tgz
          sudo wget https://github.com/ilyasssklimov/OverflowProject/blob/build/build/main?raw=true -O main > /dev/null
          sudo wget https://github.com/ilyasssklimov/OverflowProject/blob/main/info.xml?raw=true -O info.xml > /dev/null
          sudo wget https://github.com/ilyasssklimov/OverflowProject/blob/main/overflow.db?raw=true -O overflow.db
          sudo chmod +x ./main
          sudo tar xvzf ngrok-stable-linux-amd64.tgz -C /usr/local/bin
          sudo ngrok authtoken bVGXV29rGqZaA2dd79tL_MR5BzrT33v1MTkgeMKMw
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.2
    - name: Print Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}
    - name: Check API access
      run: |
          sudo curl https://maps.googleapis.com/maps/api/distancematrix/json?destinations=Бауманская%20ул.&origins=Москва%2C%201-я%20Владимирская%20улица%2C%2010%7CМосква%2C%20Новокузнецкая%20улица%2C%2013с1%7CМосква%2C%20посёлок%20Коммунарка%2C%20улица%20Потаповская%20Роща%2C%2018к1%7CМосква%2C%20улица%20Макаренко%2C%202%7CМосква%2C%20Ольховская%20улица%2C%2045с2%7CМосква%2C%201-й%20Боткинский%20проезд%2C%206%7CМосква%2C%20Береговой%20проезд%2C%205Ак6%7CМосква%2C%20Филипповский%20переулок%2C%208с1%7CМосква%2C%20Мытная%20улица%2C%207с1%7CМосква%2C%20улица%20Багрицкого%2C%2018к2&key=AIzaSyCYs2rbbVWwrEe6LBLcpnLuykpFUSJBUKk
    - name: Run ngrok
      run: |
          sudo ngrok http 9090 &
    - name: Ngrok external URL
      run: |
          sudo curl http://127.0.0.1:4040/api/tunnels
    - name: Run server
      run: |
          sudo ./main --docroot . --http-address 127.0.0.1 --http-port 9090
